#!/bin/bash

FILE_LOCATION="/home/pgrison/temp/"
FILENAME="Database.kdbx"
CURRENT_PATH=$(pwd)

VERIFICATION_URL="https://www.google.com/device"
AUTH_SCOPE=https://www.googleapis.com/auth/drive.file
OAUTH_ENDPOINT=https://oauth2.googleapis.com/device/code
EXPORT_URI=https://www.googleapis.com/drive/v3/files
IMPORT_URI=https://www.googleapis.com/upload/drive/v3/files

REMOTE_FILE_ID=$(echo $KEEPASS_DB_URL | cut -d'=' -f3)

# Easier to work in the directory of the file
cd $FILE_LOCATION

# Delete previous file just in case
if [[ -f $FILENAME ]]; then
    rm $FILENAME > /dev/null
fi

### AUTHENTICATION  ###
# Request device and user codes
response=$(curl -s -d "client_id=$CLIENT_ID&scope=$AUTH_SCOPE" $OAUTH_ENDPOINT)
# Handle the authorization server response
DEVICE_CODE=$(echo $response | grep '"device_code":' | cut -d',' -f1 | cut -d':' -f2 | cut -d'"' -f2)
USER_CODE=$(echo $response | grep '"user_code":' | cut -d',' -f2 | cut -d':' -f2 | cut -d'"' -f2)

# Display the user code
echo "Please, open $VERIFICATION_URL, enter the following code : $USER_CODE and follow instructions to grant the relevant permission to upload your file."
echo "When finish, press ENTER."
read 

# Poll Google's authorization server
response=$(curl -s -d client_id=$CLIENT_ID -d client_secret=$CLIENT_SECRET -d device_code=$DEVICE_CODE -d grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code https://accounts.google.com/o/oauth2/token)
ACCESS_TOKEN=$(echo $response | grep '"access_token"' | cut -d':' -f2 | cut -d',' -f1 | cut -d'"' -f2)
### END OF AUTHENTICATION ###

# Download the database from the Drive through Google Drive API
curl -s -X GET -L -H "Authorization: Bearer $ACCESS_TOKEN" "$EXPORT_URI/$REMOTE_FILE_ID?alt=media" >> $FILENAME

# Check if it has been correctly downloaded
if [ $? -eq 0 ]
then
    # Create a copy of the database to check if there is any modification
    cp $FILENAME $FILENAME.saved
    
    # Run the keepass2 executable
    keepass2 "$FILENAME" -pw:"$KEEPASS_DB_PWD"

    # Check the sha1 of both files. If there is any differences, it means that modifications have been made and shall be uploaded
    if [ "$(<$FILENAME sha1sum)" != "$(<$FILENAME.saved sha1sum)" ]
    then
        echo "Updating remote kee file with the local one..."

        # Update the database in the Drive
    	curl -s -X PATCH -L \
		    -H "Authorization: Bearer $ACCESS_TOKEN" \
		    -F "metadata={name :'$FILENAME'};type=application/json;charset=UTF-8" \
		    -F "file=@$FILENAME;type=application/octet-stream;" \
    		"$IMPORT_URI/$REMOTE_FILE_ID?uploadType=multipart" > /dev/null

	    if [ $? -eq 0 ]
	    then
	        echo "$FILENAME uploaded successfully."
	    else
	        echo "$FILENAME failed to be uploaded due to a wrong usage of HTTP PATCH. Check logs." >&2
	        exit -2
	    fi
    else
	    echo "$FILENAME will not be uploaded as it has not been modified."
    fi
    # Delete both files
    rm $FILENAME.saved $FILENAME
    
    # Set back to the previous path
    cd $CURRENT_PATH
    exit 0
else
    echo "Error while downloading the database." >&2
    exit -1
fi
